tasks:
  - command: |
      ./scripts/aws-auth.sh
      gp sync-done authenticate
  - command: |
      gp sync-await authenticate
      cd app 
      npm install
      npm run start

ports:
  - port: 3000
    onOpen: open-browser
    visibility: private
