tasks:
  - name: backend
    command: |
      ./scripts/aws-auth.sh
      touch backend/config.yml
      cd backend
      npm install
      node node.js

  - name: frontend
    command: |
      cd frontend 
      npm install
      npm run start

ports:
  - port: 3000
    onOpen: open-browser
    visibility: private

  - port: 3001
    onOpen: open-browser
    visibility: private
