apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYjZrdzZGSU5OdWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1UWXdOVFUwTVRsYUZ3MHpOREEwTVRRd05UVTVNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM5TDVTQlVmT1hRZVRrYi9MWEppeFByNVFyaDhoam9jc2ZWblJUa1RHMm9SdENBLzJobTBNbTJYNTEKYWdIZG56Q2FvYnZZSUxDeExDQWt0MnRtNE5BRTdCUnQ4YTZBSUlpNlF0bW5NaW5SUko2MEVndFUxaHY2Q3NJZAp2clJzaG10ZVdmZHdiMFB6MVMxdHFPQ2lvMFJjNHJSUFYxR0l4R05HanU3WHZZRzkxbFVaQjM3VFZ0Y09LMkxxCjVSV0JBSWdHek9YeGFRYnV4ZWV6dUJLTG5sNUl5WVR1ZTVEVlVmNmJhaU9WNUNqRHlRRGxNc01LcWIrSHlReE4KS3p2d0JCSVV0c2JaR1lrb0JRMWJkbDMyQ2x4VVhPbXZFNmVOekRnWmRMQ3lDRlFvTUdVUDIzYTVjdGRwZVZSVwpUTS9JR3pZSmtqeVBiSlJQdStMcm9IK1UzZWpoQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJScDVVTHcwRzFmdlFRVFpDcDNJRjJZanhMZnZ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0FaU000SG5jKwpoNm1XTGg5MTB6MGNsK2h6MDAySS8vMENnbDBTanBQQS9pUzd3Q09kQlJLcEtVdU9oUHE0NlNqczA0NGU5aUFTCmE5RzAwUTltZUhmNU1aQXRDaitIYUJMUFZPNDRHNTVjRzlhNjRWc1NCQ0kzbmpHNTFMbUJNSnBwL2xwbXg0NGMKRERadWFtSU8ycnhLMkdqb1hCSURrM08vVmNuTXlFcXRQQWFndDJDZUM1L05DT2dPUmsrNkJWZ3ViQUUrazI3bgpLcGtBakpnL2NkcDFtR1cxMDFjUHAvU2JPeEZXUXdDSVpSbkJoSkFWcGttV1E3ZFI2eFZuVDZmd2hMQ3FtbGFhClh5S1dZTmVaUWRxWTM3QzdrdGVSSDVLQ2IrT05HL2prbHZOWURaWm5qU2hsV29zVjN2elBlMTNrQitUSDFjT20KR1FEKytkQmpwakxZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://8229882335FDD25DA145FC72B279E09D.gr7.us-east-1.eks.amazonaws.com
    name: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
contexts:
  - context:
      cluster: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
      user: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
    name: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
current-context: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:us-east-1:466974194250:cluster/my-cluster-eks
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - my-cluster-eks
          - --output
          - json
        command: aws
